### ISSUE TITLE
When do you release the newest version

### ISSUE THREAD

**Issue by Tokimon** [baianat/color-fns#11]
Hi I really like your library, but right now it is a bit confusing, seeing there is no documentation, that the current code is not what has been released to NPM. The new TS structure looks really good, so I was wondering when you would release this version?

**Comment by logaretm** [comment]
We are looking to write the docs first. At least the minimal description for each function. I will work towards releasing the new version this week.

**Comment by logaretm** [comment]
@Tokimon `0.1.1` was released, there might be some issues to iron out with the bundling process.
